### ISSUE TITLE
Assembly output not protected

### ISSUE THREAD

**Issue by derekbartram** [yck1509/ConfuserEx#137]
This is likely user error, so the issue could well just be with documentation.

I have an existing .net 3.5 library, and included the code from below as per the wiki. I used ConfuserEx.exe to protect the library, however my decompiler tool showed the code had not been changed in any way. I set the base directory to the bin\Release folder where the assembly was, then added the assembly below (all inside the project tab). I did not modify anything in the Settings tab.

using System.Reflection;
using System;

[assembly: Obfuscation(Exclude = false, Feature = "preset(minimum);+ctrl flow;-anti debug;+rename(mode=letters,flatten=false);")]
[assembly: Obfuscation(Exclude = false, Feature = "random seed: Hello!")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace 'Test':-rename")]
namespace Test
{
    [Obfuscation(Exclude = false, Feature = "constants")]
    class Program
    {
        public static void Main()
        {
            Console.WriteLine("Hi");
        }
    }
}

**Comment by ToddBeaulieu** [comment]
This discussion helped me a lot. I was trying to use the CLI against the assembly that has no markup, thinking that it would obfuscate it "automatically". Now I get it.

Problem, though, if I don't use declarative markup is there a way to (assuming not) to specify the proeject, but override the source and output folders? I can't hard-code those values in the project file because they aren't always the same. For instance, on a build server with multiple agents the source folder varies. Also, the output folder is always in a new spot for that build number.

I might have to switch to declarative. 

Thank you.
