### ISSUE TITLE
ObfuscationAttribute is not respected when using a .crproj file

### ISSUE THREAD

**Issue by CoderDennis** [yck1509/ConfuserEx#139]
The class ObfAttrMarker is not used when running Confuser.CLI and passing in a .crproj file.

I tried to add calls to ParseRules and ApplyRules into ObfAttrMarker.MarkProject, but couldn't get it to work.

We need to specify protections for a given namespace and also respect ObfuscationAttribute settings.

**Comment by ErrCode** [comment]
I'm also intested in being able to combine project files and declarative obfuscation attributes, where I can specify some universal defaults within the profect file and then customize obfuscation via the ObfuscationAttributes. 

As an example, I'd like to have the SN key and password specified in the project file rather than having to do so via the ObfuscationAttributes.

**Comment by ElenaMilito** [comment]
Hopefully this feature will be added.

**Comment by KKL1982** [comment]
Hi,
I want to exclude one type from renaming. Is the following methode possible?
[assembly: Obfuscation(Feature = "type 'mynameSpace.mytype':-rename", Exclude = false)]

I want to exclude all fields in an enum from renaming. Is the following methode possible?
[assembly: Obfuscation(Feature = "Field '*' in Type 'mynameSpace.mytype':-rename", Exclude = false)]
