### ISSUE TITLE
Enum elements

### ISSUE THREAD

**Issue by acmayberry** [yck1509/ConfuserEx#152]
Are there plans to support renaming the elements of enums?  Obfuscar seems to support this but ConfuserEx leaves them untouched.

**Comment by yck1509** [comment]
It's because ConfuseEx is unable to determine whether its name would be used. For example, if ConfuserEx renames the enum elements, when you use Enum.ToString, Enum.Parse, etc., you will either get gibberish or error.
Since using ToString on enums is a quite common use case, I excludes the enum fields from renaming. I believe Obfuscar just rename them and rely on users to manually exclude them. You can force ConfuserEx to rename them by using the 'forceRen' parameter.

**Comment by acmayberry** [comment]
Thanks.  I tried forceRen, and it did not work.

**Comment by acmayberry** [comment]
Tried forceRen in the latest build, and it worked but prevented code from working.

**Comment by yck1509** [comment]
Did you apply forceRen to the enum elements, or the whole module? What kind of error occured?

**Comment by acmayberry** [comment]
I did the whole module.  I have worked it out to just the enums now.
Thanks so much for your help and fast response.  It is working great now.
