### ISSUE TITLE
ConfuserEX 0.40 triggers Kaspersky malware

### ISSUE THREAD

**Issue by NoRehab** [yck1509/ConfuserEx#154]
When I obfuscate my app at max level and add also anti-ildasm, tamper, constants, ctrl flow, anti dump, drebug, invalid metadata, ref proxy, resoures and rename.

The app works great after being obfuscated but it triggers Kaspersky immediately.

Again this is at MAX PROTECTION:
 Protection:
add constants is OK
add ctrl flow is OK
add anti dump is OK
debug not OK
invalid metadata not ok
ref proxy not ok
resources not oK
rename OK

**Comment by yck1509** [comment]
You can refer to #17 for a previous discussion on the issue of false positive. In short, since many malware author uses ConfuserEx to protect their malware from anti-viruses, the AV vendors just detects the whole family of protection methods used by ConfuserEx as harmful. I can't really think of a way to permanently fix this issue at the moment. My best advice would be consult your AV vendor and ask them about whitelisting your application.

**Comment by NoRehab** [comment]
Thanks!! I was afraid that was the answer.

**Comment by Palollo** [comment]
I avoided that problem removing the "anti tamper" protection in executable modules. Example:
```xml
<project outputDir="..\PROTECTED" baseDir=".\UNPROTECTED" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" preset="maximum" inherit="false"></rule>

  <module path="lib1.dll">
  <module path="lib2.dll">
  <module path="main.exe">
    <rule pattern="true" inherit="true">
      <protection id="anti tamper" action="remove" />
    </rule>
  </module>
</project>
```
