### ISSUE TITLE
datagridview bindings

### ISSUE THREAD

**Issue by WOT79** [yck1509/ConfuserEx#245]
When I have a bindings between the collection and datagridview and use the ConfuserEx, my program does not work, why?

App:
https://github.com/WOT79/ConfuserExDatagridview

ConfuserEx project:
```
<project outputDir="C:\ConfuserEx - bin\Confused" baseDir="C:\ConfuserEx - bin" xmlns="http://confuser.codeplex.com">
  <module path="WindowsFormsApplication1.exe">
    <rule pattern="true" preset="minimum" inherit="false" />
  </module>
</project>
```

Before
![1](https://cloud.githubusercontent.com/assets/12528605/7742115/e26e459e-ff8a-11e4-924c-dd72994de9c7.png)

After
![2](https://cloud.githubusercontent.com/assets/12528605/7742118/e85e0020-ff8a-11e4-9bbc-8ec24b6ff5d5.png)

After when dataGridView1.AutoGenerateColumns = true
![3](https://cloud.githubusercontent.com/assets/12528605/7742179/ffc33586-ff8b-11e4-93e4-53970a62f30d.png)

**Comment by XenocodeRCE** [comment]
That's because of the **Rename** protection used in the **Minimum preset**
Here are the changes you have to make in your project file :

    <rule pattern="true" preset="minimum" inherit="false" />
      <protection id="rename" action="remove" />
    </rule>

I don't know why but ConfuserEX remove(?) the **Dispose(Boolean): Void** method

![](http://i.imgur.com/EPbqtC9.png)

Your dataGridView test app works even with **Maximal Preset** if you remove **renaming protection**

**Comment by yck1509** [comment]
Hi,
As @XenocodeRCE said, you should disable the renaming protection, as the UI depends on the name of properties to display.
