### ISSUE TITLE
After confusing my exe file with ConfuserEX AVIRA antivirus detects TR/Dropper.MSIL.Gen virus inside new generated exe

### ISSUE THREAD

**Issue by agilestep** [yck1509/ConfuserEx#375]

**Comment by MurariAlex** [comment]
One of the protections provided by ConfuserEx is the anti-tamper, which encrypts the methods of your assembly. The antiviruses cannot verify the actions of the methods of your EXE when they are encrypted to tell that they are "safe" and your app isn't harmful. On top of that, many malware authors do use ConfuserEx to protect their apps, so the antivirus companies detect the protection system as a virus since thay can't assure that your program isn't harmful.

Now my notes on that:
- The **JIT** anti-tamper is ***always*** detected as a virus.
- The **normal** anti-tamper, depending on your app, and other protections like control flow ***may*** not be detected as a virus. Changing and customizing the other protections settings of ConfuserEx somehow "fools" the antiviruses. In my case, depending on the level and depth of control flow, my app may or may not trigger the anti-virus.
- Small apps and DLLs, like console apps tend to trigger the antivirus more often.

**Comment by agilestep** [comment]
Thank you for detailed answer.
Issue closed.
