### ISSUE TITLE
Constants Protection Exception (Index Out Of Range)

### ISSUE THREAD

**Issue by MurariAlex** [yck1509/ConfuserEx#387]
Hi, Ki!

After the last commits the constants protection gone bang.

The stack trace shows that the method [```EncodeConstant64```- line *#149*](https://github.com/yck1509/ConfuserEx/blob/master/Confuser.Protections/Constants/EncodePhase.cs#L149) is throwing a IOOR exception. The application that I am confusing and everything else are the same. It only occured after the update.

I will try to prepare a sample to send to you if you need it.

EDIT: I´ve changed the parameter order of the method (```lo``` and ```hi```) and it worked (but it´s not the best solution..).
I noted that the performance impact of the contants protection in the output is brutal, a task that completed in 2 sec (in the previous verison of ConfuserEx) now takes 10 sec. Don´t know if it is because of my "fix".

Thanks.

**Comment by XODE0** [comment]
i already mentioned that it isn't the best solution, the float and double constants will be missed up 
i think it is better to restore the previous "EncodeConstant64" and change the order of parameters here https://github.com/yck1509/ConfuserEx/blob/5f19e93e730fa6b25ddb3cf15636f1c397be1ad6/Confuser.Protections/Constants/EncodePhase.cs#L54 like this 

EncodeConstant64(moduleCtx, (uint)(long)entry.Key, (uint)((long)entry.Key >> 32), context.CurrentModule.CorLibTypes.Int64, entry.Value);

P.S:sorry i didn't pull a request because "EncodePhase" get messed when i push it and i couldn't find any solution for it

**Comment by yck1509** [comment]
Hi,
The reason of not changing the call site is the semantics of parameters. The parameters of EncodeConstant64 is passing high bits first, then low bits. In this sense, the call site is correct, but EncodeConstant64 saved the two parts in wrong order. I made the same mistake in encoding float/double so the error occurred.
