### ISSUE TITLE
Constants Protection Performance Impact

### ISSUE THREAD

**Issue by MurariAlex** [yck1509/ConfuserEx#400]
Hi, Ki.

After Dec 6, 2015 commits/attribute obfuscation rewriting, the constants protection started to impact the application performance brutally.
A simple console app with some cryptographic functions/math-related tasks confused with ConfuserEx after these commits takes 5x-6x longer to run some methods than ConfuserEx before these commits.
The crproj is absolutelly the same, here's the constants part.

```xml
    <protection id="constants">
      <argument name="mode" value="x86" />
      <argument name="decoderCount" value="5" />
      <argument name="cfg" value="true" />
      <argument name="elements" value="SNPI" />
    </protection>
```

The only way to achieve an acceptable performance was with the follwing config, but it makes no sense since the previous configuration worked just fine before those commits.

```xml
    <protection id="constants">
      <argument name="mode" value="x86" />
      <argument name="decoderCount" value="5" />
      <argument name="cfg" value="false" />
      <argument name="elements" value="SI" />
    </protection>
```

If you need some sample, let me know. 
Thanks!

**Comment by ab-tools** [comment]
I think this makes sense as in the commits from 6th of December this bug (reported by me, therefore I reply here ;-) ) was fixed:
https://github.com/yck1509/ConfuserEx/issues/373

So in a build before 6th of December simply just a small subset of constants were encoded although you used the "SNPI" option. Only after this bug was fixed really all constants (including primitive once like "0" or "1") were encrypted when "SNPI" is used. This obviously might have a significant impact on your algorithm performance.

You could verify this change looking at the "old" obfuscated code (using a version before 6th of December) and compare it to the "new" obfuscated code with the recent version (both using "SNPI" as option):
I would expect that a lot more constants really are encoded with the latest build.

**Comment by yck1509** [comment]
Hi,
As mentioned by @ab-tools , previous version of ConfuserEx contains a bug that cause some constants not encoded. I would suggest avoid using the 'P' elements option as it would encode much more constants.
