### ISSUE TITLE
Name Protection breaks XNA code using SpriteFont

### ISSUE THREAD

**Issue by jsmars** [yck1509/ConfuserEx#431]
Hey, awesome work on ConfuserEx! Just thought I'd add this here in case there is some kind of bug, or at least for other peoples knowledge.

I recently started using ConfuserEx on my game project built using C# and the Microsoft XNA framework, but I couldn't get a runable build even with the Minimum preset. I tried each module separately and found that it was the **Name Protection** module was breaking my code. Specifically XNA can use a method to measure the size of character of a string, and this module made those strings contain characters which were invalid for the loaded font, see error message below, and avoiding this code would mean invalid measurements.

This meant that for my project, I can use all protection **except Name Protection**.

Which leads me to two questions.

1. Is this a bug or a unavoidable result of such protection? 
If its unavoidable, what other protection am I missing without the module? Would it be a good idea to change this protection module to optionally protect all names except passed strings & chars to avoid such crashes?

2. Is my protection enough when using all modules except Name protection. Since it is part of the Minimum preset, it worries me that I can't include it.

My crash report for reference (using only Name Protection):

> System.ArgumentException: The character '‮' (0x202e) is not available in this SpriteFont. If applicable, adjust the font's start and end CharacterRegions to include this character.
> Parameter name: character
>    at Microsoft.Xna.Framework.Graphics.SpriteFont.GetIndexForCharacter(Char character)
>    at Microsoft.Xna.Framework.Graphics.SpriteFont.InternalMeasure(StringProxy& text)
>    at Microsoft.Xna.Framework.Graphics.SpriteFont.MeasureString(String text)
>    at ‫​‫⁬‌‭‬‌‮⁯​‬​‎‭‍‬‫‏⁪‪‫‫‬‮‭⁬⁫‏‬​‮⁮‭‮‎⁭‭‮‎‮.‍⁭‫‍⁮⁫⁮​‎‍‭‎⁫⁫‏‪‫‌​‏‮‍‪‫⁬‍‏⁮⁭⁯‭⁬⁪‌‪‪‬‏‏⁭‮()
>    at ‮⁯‍⁫‏‫⁫⁪⁮​‍‪‭‭⁬‍⁪‭‮‎⁬⁯‪‪‎⁪‬⁫‪‏⁪‪‭​⁮‏‌​⁪‍‮.‍⁭‫‍⁮⁫⁮​‎‍‭‎⁫⁫‏‪‫‌​‏‮‍‪‫⁬‍‏⁮⁭⁯‭⁬⁪‌‪‪‬‏‏⁭‮()
>    at ‭‪⁫⁪‌‍​⁫‭‭‭‍⁫‫⁫⁯‫‏⁫⁮‌‏‍‪⁮‫⁫⁯‌‪⁮‮‪‪‎‏⁯⁪‏‎‮.​‍‪⁯‪⁭‎‮‌⁪‎‭⁪‎‭‮⁯‪​⁫⁪‫‪⁯⁪‍‬‪‍‮‮‪‫⁫‍‫⁪‮⁫‪‮(Int32 )
>    at ‭‪⁫⁪‌‍​⁫‭‭‭‍⁫‫⁫⁯‫‏⁫⁮‌‏‍‪⁮‫⁫⁯‌‪⁮‮‪‪‎‏⁯⁪‏‎‮.⁮⁯​‎⁬⁭‪‬‍‮‏⁭‮‫‭‎⁭⁪‫‍‬⁬​⁯​⁬⁯‌‍⁮⁯‏⁭‎⁯⁪‬‎‮‭‮()
>    at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
>    at ‍⁮‪‏⁭‮‏⁬‭⁬⁫⁬⁯‫⁯⁮‭⁭‬⁮‭‫‌‭⁬‪⁯‮⁯​⁬⁯⁭⁯‮‍⁮⁪⁪‫‮.⁫‌‫‪⁯⁬⁮‮​‫‮‮⁮‭‪⁯⁯‭⁯⁫‬‭‏⁭⁭‬⁪⁬‏‏‌⁭​⁯‭⁬⁭⁭‭‏‮(String[]

**Comment by yck1509** [comment]
Hi,
It seems like you're using Reflection to obtain the name of some classes/methods and try to display them on screen. Since ConfuserEx would rename them to unreadable character, it would failed to render them. You can try excluding the referenced classes/methods from renaming or use another renaming mode.

**Comment by jsmars** [comment]
That is indeed correct, thanks!
How do exclude certain classes from renaming, or use another renaming mode?
Also, do you know the answer to my second question?

**Comment by yck1509** [comment]
If you're using the latest build, you can use apply `[Obfuscation(Exclude = False, Feature="-rename")]` to the class to exclude it. Also, you can change renaming mode using either way:
1. Declarative obfuscation:
```C#
[assembly:Obfuscation(Exclude = False, Feature="+rename(mode=letters)")]
```
2. crproj file: 
```XML
    <protection id="rename">
      <argument name="mode" value="letters" />
    </protection>
```
You can check the available modes in [the wiki](https://github.com/yck1509/ConfuserEx/wiki/Name-Protection).

I would strongly recommend you to use Name Protection as the names of classes and methods contain much information about the application, which is why it is included in Minimum preset.

**Comment by jsmars** [comment]
Thanks for the information!

It seems my sin is that I am using the C# 6.0 nameof() operator in some of my .ToString() methods that I use in certain places that are drawn on screen, as these provide a handy way to give a class name and keeps a reference in code, but when used in obfuscated code will as you say give out names with unreadable characters. To avoid making this operator unusable, maybe some workaround should be built for it?

**Comment by yck1509** [comment]
It does not seems to be caused by the nameof operator since [they are evaluated at compile time](https://stackoverflow.com/questions/26573102/is-nameof-evaluated-at-compile-time), i.e. it becomes a literal string before processed by ConfuserEx. I'll suggest you to use alternate rename mode to see if there is any difference in rendered text.

**Comment by jsmars** [comment]
Looks like it's a design flaw on my part, fetching some class names for debug purposed. Will have to make sure none of this is done for release build. Thanks for the help!
