### ISSUE TITLE
Public methods of a public object are renamed when the assembly is executable

### ISSUE THREAD

**Issue by Palollo** [yck1509/ConfuserEx#439]
This is a duplicate of the issue #311. I commented on it but I am not sure it was received because the issue is closed and there is no response. I can't reopen it.
The public methods are still renamed.

**Comment by MurariAlex** [comment]
Well, altough it is perfectly possible, cases where the EXE assembly is referenced by another assembly are rare, and IMHO, anti-pattern and somewhat a bad practice.
But, since it´s possible, there could be a flag like "renExe", default "true", to change this behavior to suit your needs. I think that the default behavior should be to rename everything is an EXE unless specified "flase" in this flag.
