### ISSUE TITLE
Could not resolve assembly

### ISSUE THREAD

**Issue by c2k-** [yck1509/ConfuserEx#469]
I am trying ConfuserEx for the first time... I followed the basic usage instructions but I am getting an error.  It seems to be related to some references.

My program is a plugin for AutoCAD and has references to 3 of it's assemblies.  They have "Copy Local" set to false per Autodesk's instruction.  I thought this might be the problem so I included those 3 assemblies with mine and tried Protect again, but this time it errors on additional assemblies referenced by those 3.

How do I get this to resolve the assemblies, or is ConfuserEx not able to work in this scenario?

Here is the original error from the Protect page output:
>  [INFO] ConfuserEx v0.6.0 Copyright (C) Ki 2014
 [INFO] Running on Microsoft Windows NT 6.1.7601 Service Pack 1, .NET Framework v4.0.30319.42000, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 10 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading 'MyTest.dll'...
 [INFO] Initializing...
[DEBUG] Building pipeline...
 [INFO] Resolving dependencies...
[ERROR] Failed to resolve dependency of 'MyTest.dll'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: accoremgd, Version=20.0.0.0, Culture=neutral, PublicKeyToken=null
   at dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule) in E:\Source\Public\Confuser2\dnlib\src\DotNet\IAssemblyResolver.cs:line 113
   at Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 264
Failed at 3:22 PM, 0:00 elapsed.

**Comment by DaxxTrias** [comment]
I also get the exact same error as you, although my process of getting the error is slightly different.

I have my own program which is reliant on some third-party libs. I am trying to use Fody.Costura to combine my application and its third-party dependencies into a single executable for consumer ease of use.

In my case I use a slight adjustment to the app.config to point the bindings to another folder where the dependencies are used. ConfuserEx has always worked fine when it could find the dependencies. (You either need to re-direct the bindings to another folder, or include them in the same folder as the program are you obfuscating.)

However by trying to use Costura I had hoped to get rid of a lot of redundant code since I could simply embed my dependencies as resource files and they get unpacked at runtime with the application. However it seems ConfuserEx is unable to locate the depencies. In you're case likely because they are not in the same folder as your application (and/or you haven't redirected to them with an app bindings change) whereas in mine it is unable to locate them since they are embedded within the file I am trying to obfuscate.

(using the absolute latest git version at the time of this writing)

**Comment by c2k-** [comment]
@DaxxTrias 
Could you give me more information on how to "re-direct the bindings to another folder"?
I am not familiar with this as it is not needed for the plugin to function.

**Comment by c2k-** [comment]
Well I was able to get it to work after I stumbled upon the "Probe Paths" setting.  I just added the location of the AutoCAD assemblies that were referenced.
This allowed the process to complete with no errors, BUT... when I went to the confused folder it was empty.
I then determined that my antivurus (Bitdefender Endpoint Security) is sending the "confused" file to the quarantine.
So I am back to not being able to use ConfuserEx. :(
