### ISSUE TITLE
What a pity...

### ISSUE THREAD

**Issue by roro2** [yck1509/ConfuserEx#534]
Why did you show this : "Confused By ConfuserEx v1.0.0" ?
Why facilitate the work of people who want to crack our programs ?
You did a very good tool  and mentioned this! I can't understand...

I downloaded the source of confuserEX 1.0.0 because I wanted to remove this.
But when I compile the project with Visual Studio, I have had so much compile errors, so I prefered to abandon.
Did you really test what you put in your .zip ? Why do we have so much compile errors ? 

Conclusion : I have to find a new obfuscator Tool which will not indicate the name of the tool used!
2 days lost Learning and integrating ConfuserEX in my project.

What a pity....

**Comment by SlowLogicBoy** [comment]
> Why did you show this : "Confused By ConfuserEx v1.0.0" ?
Why facilitate the work of people who want to crack our programs ?
You did a very good tool and mentioned this! I can't understand...

You can show or hide this attribute, if I want to crack your program I will find out that it's Obfuscated by ConfuserEx (or another obfuscator) because every obfuscator has his own footprints even, if I don't know which one is it, I can still reverse engineer it.

> I downloaded the source of confuserEX 1.0.0 because I wanted to remove this.
But when I compile the project with Visual Studio, I have had so much compile errors, so I prefered to abandon.
Did you really test what you put in your .zip ? Why do we have so much compile errors ?

Zip is generated by Github not by project developers, you need to git clone recursively to get everything you need to build project.

**Comment by MurariAlex** [comment]
@roro2 It's called _Watermarking_ and many issues here deal with this subject. Take a look at [this post](https://github.com/yck1509/ConfuserEx/issues/305#issuecomment-135749150).

ConfuserEx depends on the [dnlib](https://github.com/0xd4d/dnlib), when you download the zip package, dnlib doesn't come with the ConfuserEx source, so you have to manually download it. If you don't, you can really expect many compiler errors.

**Comment by gyrodrill** [comment]
So you download the source from Release page but not by git client?

**Comment by XenocodeRCE** [comment]
1. You are bashing ConfuserEX Watermarking, without knowing that it is not needed for people to know if your file was protected by ConfuserEX or not. If you pratice static analysis you will be able to see that ConfuserEX Control Flow Obfuscation and Constant Protection **is** unique in its way and therefore **ARE** a _kind of watermark_ since they tell the reverse engineer which protection was applied.
2. Your innapropriate skill to compile the project shall not be a part of this issue, please separate them so people will be able to help you figuring out how to compile it.
3. If you are looing for a seure and closed-source software to use please [refer to this Yck post here](https://yck1509.github.io/ConfuserEx/2016/07/01/confuserex-discontinue) or modify ConfuserEX source code

**Comment by roro2** [comment]
Hello everybody,

Finally, with all your advices, I succedeed to modify ConfuserEX source code and removed all source code concerning 'watermarking'.
As MurariAlex said, it missed me 'dnlib' , so I downloaded it and could compile ConfuserEX without problem..a big thank to him.

Now I can use ConfuserEx with my soft and I am very happy of this because I find it's a good product.

I am aware that people who really want to know how my program was obfuscated, can investigate and finally find what they want.
But I didn't want to facilitate their 'work' and maybe now some of them will be discouraged.

Thank you all for your help...
Ron
